// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Match.proto

package com.playboy.proto;

public final class Matches {
  private Matches() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Match)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 areaId = 1;</code>
     */
    boolean hasAreaId();
    /**
     * <code>required int32 areaId = 1;</code>
     */
    int getAreaId();
  }
  /**
   * Protobuf type {@code Match}
   *
   * <pre>
   * 发起匹配请求
   * </pre>
   */
  public static final class Match extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Match)
      MatchOrBuilder {
    // Use Match.newBuilder() to construct.
    private Match(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Match(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Match defaultInstance;
    public static Match getDefaultInstance() {
      return defaultInstance;
    }

    public Match getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Match(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              areaId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.playboy.proto.Matches.internal_static_Match_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.playboy.proto.Matches.internal_static_Match_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.playboy.proto.Matches.Match.class, com.playboy.proto.Matches.Match.Builder.class);
    }

    public static com.google.protobuf.Parser<Match> PARSER =
        new com.google.protobuf.AbstractParser<Match>() {
      public Match parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Match(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Match> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AREAID_FIELD_NUMBER = 1;
    private int areaId_;
    /**
     * <code>required int32 areaId = 1;</code>
     */
    public boolean hasAreaId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 areaId = 1;</code>
     */
    public int getAreaId() {
      return areaId_;
    }

    private void initFields() {
      areaId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAreaId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, areaId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, areaId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.playboy.proto.Matches.Match parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playboy.proto.Matches.Match parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playboy.proto.Matches.Match parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playboy.proto.Matches.Match parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playboy.proto.Matches.Match parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playboy.proto.Matches.Match parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.playboy.proto.Matches.Match parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.playboy.proto.Matches.Match parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.playboy.proto.Matches.Match parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playboy.proto.Matches.Match parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.playboy.proto.Matches.Match prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Match}
     *
     * <pre>
     * 发起匹配请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Match)
        com.playboy.proto.Matches.MatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.playboy.proto.Matches.internal_static_Match_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.playboy.proto.Matches.internal_static_Match_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.playboy.proto.Matches.Match.class, com.playboy.proto.Matches.Match.Builder.class);
      }

      // Construct using com.playboy.proto.Matches.Match.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        areaId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.playboy.proto.Matches.internal_static_Match_descriptor;
      }

      public com.playboy.proto.Matches.Match getDefaultInstanceForType() {
        return com.playboy.proto.Matches.Match.getDefaultInstance();
      }

      public com.playboy.proto.Matches.Match build() {
        com.playboy.proto.Matches.Match result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.playboy.proto.Matches.Match buildPartial() {
        com.playboy.proto.Matches.Match result = new com.playboy.proto.Matches.Match(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.areaId_ = areaId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.playboy.proto.Matches.Match) {
          return mergeFrom((com.playboy.proto.Matches.Match)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.playboy.proto.Matches.Match other) {
        if (other == com.playboy.proto.Matches.Match.getDefaultInstance()) return this;
        if (other.hasAreaId()) {
          setAreaId(other.getAreaId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAreaId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.playboy.proto.Matches.Match parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.playboy.proto.Matches.Match) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int areaId_ ;
      /**
       * <code>required int32 areaId = 1;</code>
       */
      public boolean hasAreaId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 areaId = 1;</code>
       */
      public int getAreaId() {
        return areaId_;
      }
      /**
       * <code>required int32 areaId = 1;</code>
       */
      public Builder setAreaId(int value) {
        bitField0_ |= 0x00000001;
        areaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 areaId = 1;</code>
       */
      public Builder clearAreaId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        areaId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Match)
    }

    static {
      defaultInstance = new Match(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Match)
  }

  public interface MatchInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MatchInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 serverId = 1;</code>
     */
    boolean hasServerId();
    /**
     * <code>required int32 serverId = 1;</code>
     */
    int getServerId();

    /**
     * <code>required int32 areaId = 2;</code>
     */
    boolean hasAreaId();
    /**
     * <code>required int32 areaId = 2;</code>
     */
    int getAreaId();

    /**
     * <code>required int64 playerId = 3;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int64 playerId = 3;</code>
     */
    long getPlayerId();
  }
  /**
   * Protobuf type {@code MatchInfo}
   *
   * <pre>
   * 简单的匹配信息
   * </pre>
   */
  public static final class MatchInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MatchInfo)
      MatchInfoOrBuilder {
    // Use MatchInfo.newBuilder() to construct.
    private MatchInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MatchInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MatchInfo defaultInstance;
    public static MatchInfo getDefaultInstance() {
      return defaultInstance;
    }

    public MatchInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MatchInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              areaId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              playerId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.playboy.proto.Matches.internal_static_MatchInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.playboy.proto.Matches.internal_static_MatchInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.playboy.proto.Matches.MatchInfo.class, com.playboy.proto.Matches.MatchInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<MatchInfo> PARSER =
        new com.google.protobuf.AbstractParser<MatchInfo>() {
      public MatchInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatchInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MatchInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <code>required int32 serverId = 1;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serverId = 1;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int AREAID_FIELD_NUMBER = 2;
    private int areaId_;
    /**
     * <code>required int32 areaId = 2;</code>
     */
    public boolean hasAreaId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 areaId = 2;</code>
     */
    public int getAreaId() {
      return areaId_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 3;
    private long playerId_;
    /**
     * <code>required int64 playerId = 3;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 playerId = 3;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    private void initFields() {
      serverId_ = 0;
      areaId_ = 0;
      playerId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAreaId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, areaId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, playerId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, areaId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, playerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.playboy.proto.Matches.MatchInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playboy.proto.Matches.MatchInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playboy.proto.Matches.MatchInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playboy.proto.Matches.MatchInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.playboy.proto.Matches.MatchInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playboy.proto.Matches.MatchInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.playboy.proto.Matches.MatchInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MatchInfo}
     *
     * <pre>
     * 简单的匹配信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MatchInfo)
        com.playboy.proto.Matches.MatchInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.playboy.proto.Matches.internal_static_MatchInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.playboy.proto.Matches.internal_static_MatchInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.playboy.proto.Matches.MatchInfo.class, com.playboy.proto.Matches.MatchInfo.Builder.class);
      }

      // Construct using com.playboy.proto.Matches.MatchInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        areaId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.playboy.proto.Matches.internal_static_MatchInfo_descriptor;
      }

      public com.playboy.proto.Matches.MatchInfo getDefaultInstanceForType() {
        return com.playboy.proto.Matches.MatchInfo.getDefaultInstance();
      }

      public com.playboy.proto.Matches.MatchInfo build() {
        com.playboy.proto.Matches.MatchInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.playboy.proto.Matches.MatchInfo buildPartial() {
        com.playboy.proto.Matches.MatchInfo result = new com.playboy.proto.Matches.MatchInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.areaId_ = areaId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.playerId_ = playerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.playboy.proto.Matches.MatchInfo) {
          return mergeFrom((com.playboy.proto.Matches.MatchInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.playboy.proto.Matches.MatchInfo other) {
        if (other == com.playboy.proto.Matches.MatchInfo.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasAreaId()) {
          setAreaId(other.getAreaId());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerId()) {
          
          return false;
        }
        if (!hasAreaId()) {
          
          return false;
        }
        if (!hasPlayerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.playboy.proto.Matches.MatchInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.playboy.proto.Matches.MatchInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverId_ ;
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private int areaId_ ;
      /**
       * <code>required int32 areaId = 2;</code>
       */
      public boolean hasAreaId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 areaId = 2;</code>
       */
      public int getAreaId() {
        return areaId_;
      }
      /**
       * <code>required int32 areaId = 2;</code>
       */
      public Builder setAreaId(int value) {
        bitField0_ |= 0x00000002;
        areaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 areaId = 2;</code>
       */
      public Builder clearAreaId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        areaId_ = 0;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <code>required int64 playerId = 3;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 playerId = 3;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int64 playerId = 3;</code>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000004;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 playerId = 3;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MatchInfo)
    }

    static {
      defaultInstance = new MatchInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MatchInfo)
  }

  public interface MatchResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MatchResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    java.util.List<com.playboy.proto.Matches.MatchInfo> 
        getInfosList();
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    com.playboy.proto.Matches.MatchInfo getInfos(int index);
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    java.util.List<? extends com.playboy.proto.Matches.MatchInfoOrBuilder> 
        getInfosOrBuilderList();
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    com.playboy.proto.Matches.MatchInfoOrBuilder getInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MatchResult}
   *
   * <pre>
   * 返回匹配结果
   * </pre>
   */
  public static final class MatchResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MatchResult)
      MatchResultOrBuilder {
    // Use MatchResult.newBuilder() to construct.
    private MatchResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MatchResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MatchResult defaultInstance;
    public static MatchResult getDefaultInstance() {
      return defaultInstance;
    }

    public MatchResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MatchResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                infos_ = new java.util.ArrayList<com.playboy.proto.Matches.MatchInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              infos_.add(input.readMessage(com.playboy.proto.Matches.MatchInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.playboy.proto.Matches.internal_static_MatchResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.playboy.proto.Matches.internal_static_MatchResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.playboy.proto.Matches.MatchResult.class, com.playboy.proto.Matches.MatchResult.Builder.class);
    }

    public static com.google.protobuf.Parser<MatchResult> PARSER =
        new com.google.protobuf.AbstractParser<MatchResult>() {
      public MatchResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatchResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MatchResult> getParserForType() {
      return PARSER;
    }

    public static final int INFOS_FIELD_NUMBER = 1;
    private java.util.List<com.playboy.proto.Matches.MatchInfo> infos_;
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    public java.util.List<com.playboy.proto.Matches.MatchInfo> getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    public java.util.List<? extends com.playboy.proto.Matches.MatchInfoOrBuilder> 
        getInfosOrBuilderList() {
      return infos_;
    }
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    public com.playboy.proto.Matches.MatchInfo getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated .MatchInfo infos = 1;</code>
     */
    public com.playboy.proto.Matches.MatchInfoOrBuilder getInfosOrBuilder(
        int index) {
      return infos_.get(index);
    }

    private void initFields() {
      infos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getInfosCount(); i++) {
        if (!getInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < infos_.size(); i++) {
        output.writeMessage(1, infos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < infos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, infos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.playboy.proto.Matches.MatchResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playboy.proto.Matches.MatchResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playboy.proto.Matches.MatchResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playboy.proto.Matches.MatchResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.playboy.proto.Matches.MatchResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playboy.proto.Matches.MatchResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.playboy.proto.Matches.MatchResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MatchResult}
     *
     * <pre>
     * 返回匹配结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MatchResult)
        com.playboy.proto.Matches.MatchResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.playboy.proto.Matches.internal_static_MatchResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.playboy.proto.Matches.internal_static_MatchResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.playboy.proto.Matches.MatchResult.class, com.playboy.proto.Matches.MatchResult.Builder.class);
      }

      // Construct using com.playboy.proto.Matches.MatchResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          infosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.playboy.proto.Matches.internal_static_MatchResult_descriptor;
      }

      public com.playboy.proto.Matches.MatchResult getDefaultInstanceForType() {
        return com.playboy.proto.Matches.MatchResult.getDefaultInstance();
      }

      public com.playboy.proto.Matches.MatchResult build() {
        com.playboy.proto.Matches.MatchResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.playboy.proto.Matches.MatchResult buildPartial() {
        com.playboy.proto.Matches.MatchResult result = new com.playboy.proto.Matches.MatchResult(this);
        int from_bitField0_ = bitField0_;
        if (infosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            infos_ = java.util.Collections.unmodifiableList(infos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.infos_ = infos_;
        } else {
          result.infos_ = infosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.playboy.proto.Matches.MatchResult) {
          return mergeFrom((com.playboy.proto.Matches.MatchResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.playboy.proto.Matches.MatchResult other) {
        if (other == com.playboy.proto.Matches.MatchResult.getDefaultInstance()) return this;
        if (infosBuilder_ == null) {
          if (!other.infos_.isEmpty()) {
            if (infos_.isEmpty()) {
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInfosIsMutable();
              infos_.addAll(other.infos_);
            }
            onChanged();
          }
        } else {
          if (!other.infos_.isEmpty()) {
            if (infosBuilder_.isEmpty()) {
              infosBuilder_.dispose();
              infosBuilder_ = null;
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              infosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfosFieldBuilder() : null;
            } else {
              infosBuilder_.addAllMessages(other.infos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getInfosCount(); i++) {
          if (!getInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.playboy.proto.Matches.MatchResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.playboy.proto.Matches.MatchResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.playboy.proto.Matches.MatchInfo> infos_ =
        java.util.Collections.emptyList();
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          infos_ = new java.util.ArrayList<com.playboy.proto.Matches.MatchInfo>(infos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.playboy.proto.Matches.MatchInfo, com.playboy.proto.Matches.MatchInfo.Builder, com.playboy.proto.Matches.MatchInfoOrBuilder> infosBuilder_;

      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public java.util.List<com.playboy.proto.Matches.MatchInfo> getInfosList() {
        if (infosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(infos_);
        } else {
          return infosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public int getInfosCount() {
        if (infosBuilder_ == null) {
          return infos_.size();
        } else {
          return infosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public com.playboy.proto.Matches.MatchInfo getInfos(int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);
        } else {
          return infosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder setInfos(
          int index, com.playboy.proto.Matches.MatchInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.set(index, value);
          onChanged();
        } else {
          infosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder setInfos(
          int index, com.playboy.proto.Matches.MatchInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.set(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder addInfos(com.playboy.proto.Matches.MatchInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(value);
          onChanged();
        } else {
          infosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder addInfos(
          int index, com.playboy.proto.Matches.MatchInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(index, value);
          onChanged();
        } else {
          infosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder addInfos(
          com.playboy.proto.Matches.MatchInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder addInfos(
          int index, com.playboy.proto.Matches.MatchInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<? extends com.playboy.proto.Matches.MatchInfo> values) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, infos_);
          onChanged();
        } else {
          infosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder clearInfos() {
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          infosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public Builder removeInfos(int index) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.remove(index);
          onChanged();
        } else {
          infosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public com.playboy.proto.Matches.MatchInfo.Builder getInfosBuilder(
          int index) {
        return getInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public com.playboy.proto.Matches.MatchInfoOrBuilder getInfosOrBuilder(
          int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);  } else {
          return infosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public java.util.List<? extends com.playboy.proto.Matches.MatchInfoOrBuilder> 
           getInfosOrBuilderList() {
        if (infosBuilder_ != null) {
          return infosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(infos_);
        }
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public com.playboy.proto.Matches.MatchInfo.Builder addInfosBuilder() {
        return getInfosFieldBuilder().addBuilder(
            com.playboy.proto.Matches.MatchInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public com.playboy.proto.Matches.MatchInfo.Builder addInfosBuilder(
          int index) {
        return getInfosFieldBuilder().addBuilder(
            index, com.playboy.proto.Matches.MatchInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .MatchInfo infos = 1;</code>
       */
      public java.util.List<com.playboy.proto.Matches.MatchInfo.Builder> 
           getInfosBuilderList() {
        return getInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.playboy.proto.Matches.MatchInfo, com.playboy.proto.Matches.MatchInfo.Builder, com.playboy.proto.Matches.MatchInfoOrBuilder> 
          getInfosFieldBuilder() {
        if (infosBuilder_ == null) {
          infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.playboy.proto.Matches.MatchInfo, com.playboy.proto.Matches.MatchInfo.Builder, com.playboy.proto.Matches.MatchInfoOrBuilder>(
                  infos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          infos_ = null;
        }
        return infosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MatchResult)
    }

    static {
      defaultInstance = new MatchResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MatchResult)
  }

  public interface MatchDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MatchDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required .PlayerInfo info = 2;</code>
     */
    boolean hasInfo();
    /**
     * <code>required .PlayerInfo info = 2;</code>
     */
    com.playboy.proto.Players.PlayerInfo getInfo();
    /**
     * <code>required .PlayerInfo info = 2;</code>
     */
    com.playboy.proto.Players.PlayerInfoOrBuilder getInfoOrBuilder();
  }
  /**
   * Protobuf type {@code MatchDetail}
   *
   * <pre>
   * 单条匹配详细信息
   * </pre>
   */
  public static final class MatchDetail extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MatchDetail)
      MatchDetailOrBuilder {
    // Use MatchDetail.newBuilder() to construct.
    private MatchDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MatchDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MatchDetail defaultInstance;
    public static MatchDetail getDefaultInstance() {
      return defaultInstance;
    }

    public MatchDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MatchDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.playboy.proto.Players.PlayerInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(com.playboy.proto.Players.PlayerInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.playboy.proto.Matches.internal_static_MatchDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.playboy.proto.Matches.internal_static_MatchDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.playboy.proto.Matches.MatchDetail.class, com.playboy.proto.Matches.MatchDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<MatchDetail> PARSER =
        new com.google.protobuf.AbstractParser<MatchDetail>() {
      public MatchDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatchDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MatchDetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int INFO_FIELD_NUMBER = 2;
    private com.playboy.proto.Players.PlayerInfo info_;
    /**
     * <code>required .PlayerInfo info = 2;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .PlayerInfo info = 2;</code>
     */
    public com.playboy.proto.Players.PlayerInfo getInfo() {
      return info_;
    }
    /**
     * <code>required .PlayerInfo info = 2;</code>
     */
    public com.playboy.proto.Players.PlayerInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    private void initFields() {
      id_ = 0L;
      info_ = com.playboy.proto.Players.PlayerInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, info_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.playboy.proto.Matches.MatchDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playboy.proto.Matches.MatchDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playboy.proto.Matches.MatchDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playboy.proto.Matches.MatchDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.playboy.proto.Matches.MatchDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.playboy.proto.Matches.MatchDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playboy.proto.Matches.MatchDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.playboy.proto.Matches.MatchDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MatchDetail}
     *
     * <pre>
     * 单条匹配详细信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MatchDetail)
        com.playboy.proto.Matches.MatchDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.playboy.proto.Matches.internal_static_MatchDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.playboy.proto.Matches.internal_static_MatchDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.playboy.proto.Matches.MatchDetail.class, com.playboy.proto.Matches.MatchDetail.Builder.class);
      }

      // Construct using com.playboy.proto.Matches.MatchDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (infoBuilder_ == null) {
          info_ = com.playboy.proto.Players.PlayerInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.playboy.proto.Matches.internal_static_MatchDetail_descriptor;
      }

      public com.playboy.proto.Matches.MatchDetail getDefaultInstanceForType() {
        return com.playboy.proto.Matches.MatchDetail.getDefaultInstance();
      }

      public com.playboy.proto.Matches.MatchDetail build() {
        com.playboy.proto.Matches.MatchDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.playboy.proto.Matches.MatchDetail buildPartial() {
        com.playboy.proto.Matches.MatchDetail result = new com.playboy.proto.Matches.MatchDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.playboy.proto.Matches.MatchDetail) {
          return mergeFrom((com.playboy.proto.Matches.MatchDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.playboy.proto.Matches.MatchDetail other) {
        if (other == com.playboy.proto.Matches.MatchDetail.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasInfo()) {
          
          return false;
        }
        if (!getInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.playboy.proto.Matches.MatchDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.playboy.proto.Matches.MatchDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private com.playboy.proto.Players.PlayerInfo info_ = com.playboy.proto.Players.PlayerInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.playboy.proto.Players.PlayerInfo, com.playboy.proto.Players.PlayerInfo.Builder, com.playboy.proto.Players.PlayerInfoOrBuilder> infoBuilder_;
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      public com.playboy.proto.Players.PlayerInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      public Builder setInfo(com.playboy.proto.Players.PlayerInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      public Builder setInfo(
          com.playboy.proto.Players.PlayerInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      public Builder mergeInfo(com.playboy.proto.Players.PlayerInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              info_ != com.playboy.proto.Players.PlayerInfo.getDefaultInstance()) {
            info_ =
              com.playboy.proto.Players.PlayerInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = com.playboy.proto.Players.PlayerInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      public com.playboy.proto.Players.PlayerInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      public com.playboy.proto.Players.PlayerInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>required .PlayerInfo info = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.playboy.proto.Players.PlayerInfo, com.playboy.proto.Players.PlayerInfo.Builder, com.playboy.proto.Players.PlayerInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.playboy.proto.Players.PlayerInfo, com.playboy.proto.Players.PlayerInfo.Builder, com.playboy.proto.Players.PlayerInfoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MatchDetail)
    }

    static {
      defaultInstance = new MatchDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MatchDetail)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Match_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Match_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MatchInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MatchInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MatchResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MatchResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MatchDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MatchDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Match.proto\032\014Player.proto\"\027\n\005Match\022\016\n\006" +
      "areaId\030\001 \002(\005\"?\n\tMatchInfo\022\020\n\010serverId\030\001 " +
      "\002(\005\022\016\n\006areaId\030\002 \002(\005\022\020\n\010playerId\030\003 \002(\003\"(\n" +
      "\013MatchResult\022\031\n\005infos\030\001 \003(\0132\n.MatchInfo\"" +
      "4\n\013MatchDetail\022\n\n\002id\030\001 \002(\003\022\031\n\004info\030\002 \002(\013" +
      "2\013.PlayerInfoB\034\n\021com.playboy.protoB\007Matc" +
      "hes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.playboy.proto.Players.getDescriptor(),
        }, assigner);
    internal_static_Match_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Match_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Match_descriptor,
        new java.lang.String[] { "AreaId", });
    internal_static_MatchInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MatchInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MatchInfo_descriptor,
        new java.lang.String[] { "ServerId", "AreaId", "PlayerId", });
    internal_static_MatchResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MatchResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MatchResult_descriptor,
        new java.lang.String[] { "Infos", });
    internal_static_MatchDetail_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MatchDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MatchDetail_descriptor,
        new java.lang.String[] { "Id", "Info", });
    com.playboy.proto.Players.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
