// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto

package com.playboy.proto;

public final class MessageTypes {
  private MessageTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MessageType}
   *
   * <pre>
   * 消息类型;
   * </pre>
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CG_LOGIN = 1001;</code>
     *
     * <pre>
     * request login
     * </pre>
     */
    CG_LOGIN(0, 1001),
    /**
     * <code>GC_LOGIN_RESULT = 1002;</code>
     *
     * <pre>
     * login result
     * </pre>
     */
    GC_LOGIN_RESULT(1, 1002),
    /**
     * <code>CG_MATCH = 1003;</code>
     *
     * <pre>
     * match
     * </pre>
     */
    CG_MATCH(2, 1003),
    /**
     * <code>GC_MATCH_RESULT = 1004;</code>
     *
     * <pre>
     * match result
     * </pre>
     */
    GC_MATCH_RESULT(3, 1004),
    ;

    /**
     * <code>CG_LOGIN = 1001;</code>
     *
     * <pre>
     * request login
     * </pre>
     */
    public static final int CG_LOGIN_VALUE = 1001;
    /**
     * <code>GC_LOGIN_RESULT = 1002;</code>
     *
     * <pre>
     * login result
     * </pre>
     */
    public static final int GC_LOGIN_RESULT_VALUE = 1002;
    /**
     * <code>CG_MATCH = 1003;</code>
     *
     * <pre>
     * match
     * </pre>
     */
    public static final int CG_MATCH_VALUE = 1003;
    /**
     * <code>GC_MATCH_RESULT = 1004;</code>
     *
     * <pre>
     * match result
     * </pre>
     */
    public static final int GC_MATCH_RESULT_VALUE = 1004;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 1001: return CG_LOGIN;
        case 1002: return GC_LOGIN_RESULT;
        case 1003: return CG_MATCH;
        case 1004: return GC_MATCH_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.playboy.proto.MessageTypes.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MessageType.proto*W\n\013MessageType\022\r\n\010CG" +
      "_LOGIN\020\351\007\022\024\n\017GC_LOGIN_RESULT\020\352\007\022\r\n\010CG_MA" +
      "TCH\020\353\007\022\024\n\017GC_MATCH_RESULT\020\354\007B!\n\021com.play" +
      "boy.protoB\014MessageTypes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
